---
title: "Traffic Stop Analysis"
author: "Sara Stoudt"
date: "3/9/2021"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F, fig.width=8, fig.height=8)
```

## Setup

```{r}
#install.packages("tidyverse") ## install if haven't already done so
#install.pacakges("mgcv") ## install if haven't already done so
#install.pacakges("lubridate") ## install if haven't already done so

library(tidyverse)
library(mgcv)
library(lubridate)
```

```{r}
data <- read.csv("../Data/dailyStops.csv")

data$date2 <- as.Date(as.character(data$date2)) ## Date class rather than factor

data$day_of_week <- factor(data$day_of_week, levels = levels(data$day_of_week)[c(2, 6, 7, 5, 1, 3, 4)]) ## relevel Monday onward 
```

## Exploratory Data Analysis

```{r}
## Slide 4 Figure
ggplot(data, aes(x = date2, y = daily_num_stops)) +
  facet_wrap(race ~ stop_purpose2, scales = "free_y", ncol = 2) +
  geom_point() +
  geom_vline(xintercept = as.Date("2005-12-09"), lty = 2) +
  theme_minimal(base_size = 14) +
  theme(
    legend.title = element_blank(), # legend.position = "bottom" #,
    axis.text.x = element_text(angle = 30, hjust = 1)
  ) +
  labs(y = "Number of stops", x = "")

```

## Linear Model

```{r}
## Slide 5
linear_model <- lm(daily_num_stops ~ driver_race + post_policy + driver_race * post_policy + day_of_week + month, data = data)

summary(linear_model)

data$predLM <- predict(linear_model) ## store predicted values

```

```{r}
ggplot(data, aes(x = date2, y = daily_num_stops)) +
  facet_wrap(~race, scales = "free_y", ncol = 1) +
  geom_point() +
  geom_line(aes(x = date2, y = predLM, col = day_of_week)) +
  geom_vline(xintercept = as.Date("2005-12-09"), lty = 2) +
  theme_minimal(base_size = 14) +
  theme(
    legend.title = element_blank(), # legend.position = "bottom" #,
    axis.text.x = element_text(angle = 30, hjust = 1)
  ) +
  labs(y = "Number of stops", x = "")

```

## Generalized Linear Model

```{r}
## Slide 6
generalized_linear_model <- glm(daily_num_stops ~ driver_race + post_policy + driver_race * post_policy + day_of_week + month, data = data, family = "quasipoisson")
summary(generalized_linear_model)

data$predGLM <- predict(generalized_linear_model, type = "response") ## store predicted values on response scale
```

```{r}
ggplot(data, aes(x = date2, y = daily_num_stops)) +
  facet_wrap(~race, scales = "free_y", ncol = 1) +
  geom_point() +
  geom_line(aes(date2, predGLM, col = day_of_week)) +
  geom_vline(xintercept = as.Date("2005-12-09"), lty = 2) +
  theme_minimal(base_size = 14) +
  theme(
    legend.title = element_blank(), # legend.position = "bottom" #,
    axis.text.x = element_text(angle = 30, hjust = 1)
  ) +
  labs(y = "Number of stops", x = "")

```

## Generalized Additive Model

```{r}
## Slide 10

data$day_of_week_num <- as.numeric(data$day_of_week) ## now want to allow smoothness across days of week rather than a separate coefficient for each day

generalized_additive_model <- gam(daily_num_stops ~ driver_race + post_policy + driver_race * post_policy + s(day_of_week_num, bs = "cc", k = 4) + s(month, bs = "cc"), data = data, family = "quasipoisson")

summary(generalized_additive_model)

data$predGAM <- predict(generalized_additive_model, type = "response")

```

```{r}
ggplot(data, aes(x = date2, y = daily_num_stops)) +
  facet_wrap(~race, scales = "free_y", ncol = 1) +
  geom_point() +
  geom_line(aes(date2, predGAM, col = day_of_week)) +
  geom_vline(xintercept = as.Date("2005-12-09"), lty = 2) +
  theme_minimal(base_size = 14) +
  theme(
    legend.title = element_blank(), # legend.position = "bottom" #,
    axis.text.x = element_text(angle = 30, hjust = 1)
  ) +
  labs(y = "Number of stops", x = "")

```

```{r}
plot(generalized_additive_model, rug = T)
```

```{r}
gam.check(generalized_additive_model)
```



```{r}
## Slide 14
data$doy <- yday(data$stop_date)

generalized_additive_model2 <- gam(daily_num_stops ~ driver_race + post_policy + driver_race * post_policy + s(doy, bs = "cc") + s(day, bs = "cc") + s(day_of_week_num, bs = "cc", k = 4), data = data, family = "quasipoisson")

summary(generalized_additive_model2)

data$predGAM2 <- predict(generalized_additive_model2, type = "response")

```

```{r}
ggplot(data, aes(x = date2, y = daily_num_stops)) +
  facet_wrap(~race, scales = "free_y", ncol = 1) +
  geom_point() +
  geom_line(aes(date2, predGAM2, col = day_of_week)) +
  geom_vline(xintercept = as.Date("2005-12-09"), lty = 2) +
  theme_minimal(base_size = 14) +
  theme(
    legend.title = element_blank(), # legend.position = "bottom" #,
    axis.text.x = element_text(angle = 30, hjust = 1)
  ) +
  labs(y = "Number of stops", x = "")

```

```{r}
plot(generalized_additive_model2, rug = T)
```

```{r}
gam.check(generalized_additive_model2)
```